[variables]
NIXPACKS_PHP_VERSION = "8.4"
NIXPACKS_NODE_VERSION = "20"
COMPOSER_ALLOW_SUPERUSER = "1"

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer clear-cache",
    "composer install --no-dev --optimize-autoloader",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"